/**
 * DFU package (ZIP) parser.
 *
 * Parses the ZIP file generated by adafruit-nrfutil containing
 * a manifest.json, init packet (.dat), and firmware binary (.bin).
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

import JSZip from "jszip";
import { DfuUpdateMode } from "./dfu-protocol.js";

/** Firmware image extracted from a DFU package */
export interface DfuFirmwareImage {
  type: number;
  initPacket: Uint8Array;
  firmware: Uint8Array;
  softdeviceSize: number;
  bootloaderSize: number;
  applicationSize: number;
}

/** Manifest entry for a single firmware type */
interface ManifestEntry {
  bin_file: string;
  dat_file: string;
  sd_size?: number;
  bl_size?: number;
}

/** Manifest structure inside the ZIP */
interface DfuManifest {
  manifest: {
    application?: ManifestEntry;
    softdevice?: ManifestEntry;
    bootloader?: ManifestEntry;
    softdevice_bootloader?: ManifestEntry;
  };
}

/**
 * Parse a DFU package ZIP and extract firmware images.
 *
 * @param zipData - Raw ZIP file data
 * @returns Array of firmware images to flash (in order)
 */
export async function parseDfuPackage(
  zipData: ArrayBuffer
): Promise<DfuFirmwareImage[]> {
  const zip = await JSZip.loadAsync(zipData);

  // Read manifest
  const manifestFile = zip.file("manifest.json");
  if (!manifestFile) {
    throw new Error("DFU package does not contain manifest.json");
  }

  const manifestText = await manifestFile.async("text");
  const manifest: DfuManifest = JSON.parse(manifestText);

  if (!manifest.manifest) {
    throw new Error("Invalid manifest format");
  }

  const images: DfuFirmwareImage[] = [];

  // Extract images in DFU order: SD+BL → SD → BL → App
  if (manifest.manifest.softdevice_bootloader) {
    images.push(
      await extractImage(
        zip,
        manifest.manifest.softdevice_bootloader,
        DfuUpdateMode.SD_BL
      )
    );
  }

  if (manifest.manifest.softdevice) {
    images.push(
      await extractImage(
        zip,
        manifest.manifest.softdevice,
        DfuUpdateMode.SOFTDEVICE
      )
    );
  }

  if (manifest.manifest.bootloader) {
    images.push(
      await extractImage(
        zip,
        manifest.manifest.bootloader,
        DfuUpdateMode.BOOTLOADER
      )
    );
  }

  if (manifest.manifest.application) {
    images.push(
      await extractImage(
        zip,
        manifest.manifest.application,
        DfuUpdateMode.APPLICATION
      )
    );
  }

  if (images.length === 0) {
    throw new Error("No firmware images found in manifest");
  }

  return images;
}

/**
 * Extract a single firmware image from the ZIP.
 */
async function extractImage(
  zip: JSZip,
  entry: ManifestEntry,
  type: number
): Promise<DfuFirmwareImage> {
  const binFile = zip.file(entry.bin_file);
  const datFile = zip.file(entry.dat_file);

  if (!binFile) {
    throw new Error(`Missing firmware binary: ${entry.bin_file}`);
  }
  if (!datFile) {
    throw new Error(`Missing init packet: ${entry.dat_file}`);
  }

  const firmware = new Uint8Array(await binFile.async("arraybuffer"));
  const initPacket = new Uint8Array(await datFile.async("arraybuffer"));

  let softdeviceSize = 0;
  let bootloaderSize = 0;
  let applicationSize = 0;

  switch (type) {
    case DfuUpdateMode.APPLICATION:
      applicationSize = firmware.length;
      break;
    case DfuUpdateMode.SOFTDEVICE:
      softdeviceSize = firmware.length;
      break;
    case DfuUpdateMode.BOOTLOADER:
      bootloaderSize = firmware.length;
      break;
    case DfuUpdateMode.SD_BL:
      softdeviceSize = entry.sd_size ?? 0;
      bootloaderSize = entry.bl_size ?? 0;
      if (softdeviceSize + bootloaderSize !== firmware.length) {
        throw new Error(
          `SD+BL size mismatch: sd(${softdeviceSize}) + bl(${bootloaderSize}) != firmware(${firmware.length})`
        );
      }
      break;
  }

  return {
    type,
    initPacket,
    firmware,
    softdeviceSize,
    bootloaderSize,
    applicationSize,
  };
}